# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='user',
            field=models.UUIDField(blank=True, help_text='The UUID of the user who created this revision.', null=True, verbose_name='user'),
        ),
    ]
